name: CI Pipeline
on: [push] 
jobs:
 build:
  runs-on: ubunty-latest
 steps:
  -users: actions/checkout@v4
  -name: Run a script
  run: echo "Hello, GitHub Actions!"
name: Build & Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test
